package com.sqldomaingen.schemaValidation;

import com.sqldomaingen.validation.EntitySchemaValidator;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests SQL schema parsing edge cases used by EntitySchemaValidator.
 */
class EntitySchemaValidatorParseSchemaTest {

    @TempDir
    Path tempDir;

    /**
     * Verifies that CREATE TABLE parsing does not stop at nested parentheses
     * inside IDENTITY declarations or SQL data types.
     *
     * @throws Exception when test files cannot be written
     */
    @Test
    void shouldValidateColumnsAfterIdentityAndTimestampColumns() throws Exception {
        Path schemaPath = tempDir.resolve("schema.sql");
        Path generatedJavaRoot = tempDir.resolve("generated/src/main/java");

        Path entityDir = generatedJavaRoot.resolve("gr/knowledge/pepTest/entity");
        Files.createDirectories(entityDir);

        Files.writeString(schemaPath, """
                CREATE TABLE neo_schema.employee_attendance (
                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                    employee_id int8 NOT NULL,
                    check_in_time timestamp NOT NULL,
                    check_out_time timestamp NULL,
                    attendance_date date NOT NULL,
                    CONSTRAINT employee_attendance_pkey PRIMARY KEY (id),
                    CONSTRAINT fk_employee_attendance_employee FOREIGN KEY (employee_id)
                        REFERENCES neo_schema.employee(id) ON DELETE CASCADE
                );
                """);

        Files.writeString(entityDir.resolve("EmployeeAttendance.java"), """
                package gr.knowledge.pepTest.entity;

                import jakarta.persistence.*;
                import java.time.LocalDate;
                import java.time.LocalDateTime;

                @Entity
                @Table(name = "employee_attendance")
                public class EmployeeAttendance {

                    @Id
                    @GeneratedValue(strategy = GenerationType.IDENTITY)
                    @Column(name = "id", nullable = false)
                    private Long id;

                    @Column(name = "employee_id", nullable = false)
                    private Long employeeId;

                    @Column(name = "check_in_time", nullable = false)
                    private LocalDateTime checkInTime;

                    @Column(name = "check_out_time")
                    private LocalDateTime checkOutTime;

                    @Column(name = "attendance_date", nullable = false)
                    private LocalDate attendanceDate;
                }
                """);

        EntitySchemaValidator validator = new EntitySchemaValidator(schemaPath, generatedJavaRoot);

        List<String> violations = validator.validate();

        assertTrue(
                violations.stream().noneMatch(violation -> violation.contains("checkInTime")),
                () -> "checkInTime should be resolved from check_in_time. Violations: " + violations
        );

        assertTrue(
                violations.stream().noneMatch(violation -> violation.contains("checkOutTime")),
                () -> "checkOutTime should be resolved from check_out_time. Violations: " + violations
        );
    }
}