# application.properties

# Logging configuration
logging.level.root=INFO
logging.level.com.sqldomaingen=INFO
logging.level.com.sqldomaingen.parser=INFO

# Output directory for generated entities
generator.output.directory=target/generated-sources/entities

# Package name for generated entities
generator.package.name=com.example.entities

# Flag for enabling Lombok builder pattern
generator.enable.builder=true

# Database settings (?? ?????????? ????????)
database.url=jdbc:postgresql://localhost:5432/your_database
database.username=your_username
database.password=your_password
database.driver=org.postgresql.Driver
